spring:
  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

  datasource:
    url: jdbc:postgresql://localhost:5432/eurekaserver
    username: jeendale
    password: 12345678!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # 데이터베이스 스키마 자동 업데이트 (필요에 따라 create, validate 등으로 변경 가능)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true # PostgreSQL 전용 방언 사용
    show-sql: true

service:
  jwt:
    access-expiration: 3600000
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"


server:
  port: 19095